#############################################################################
# Makefile for building: woWop
# Generated by qmake (2.01a) (Qt 4.7.4) on: Sat May 26 14:49:53 2012
# Project:  woWop.pro
# Template: app
# Command: /usr/local/bin/qmake-qt4 -spec ../../../local/share/qt4/mkspecs/freebsd-g++ -o Makefile woWop.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_WEBKIT_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W $(DEFINES)
INCPATH       = -I../../../local/share/qt4/mkspecs/freebsd-g++ -I. -I../../../local/include/qt4/QtCore -I../../../local/include/qt4/QtGui -I../../../local/include/qt4/QtWebKit -I../../../local/include/qt4 -I../../../local/include/mongo -I. -I. -I../../../local/include/qt4 -I../../../local/include
LINK          = g++
LFLAGS        = -Wl,-O1 -pthread -Wl,-rpath,/usr/local/lib/qt4
LIBS          = $(SUBLIBS)  -L/usr/local/lib/qt4 -L/usr/local/lib -lmongoclient -lQtWebKit -lQtGui -L/usr/local/lib/qt4 -L/usr/local/lib -lQtCore 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/local/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		treeitem.cpp \
		treemodel.cpp moc_mainwindow.cpp \
		moc_treemodel.cpp
OBJECTS       = main.o \
		mainwindow.o \
		treeitem.o \
		treemodel.o \
		moc_mainwindow.o \
		moc_treemodel.o
DIST          = ../../../local/share/qt4/mkspecs/common/g++.conf \
		../../../local/share/qt4/mkspecs/common/unix.conf \
		../../../local/share/qt4/mkspecs/qconfig.pri \
		../../../local/share/qt4/mkspecs/modules/qt_phonon.pri \
		../../../local/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		../../../local/share/qt4/mkspecs/features/qt_functions.prf \
		../../../local/share/qt4/mkspecs/features/qt_config.prf \
		../../../local/share/qt4/mkspecs/features/exclusive_builds.prf \
		../../../local/share/qt4/mkspecs/features/default_pre.prf \
		../../../local/share/qt4/mkspecs/features/release.prf \
		../../../local/share/qt4/mkspecs/features/default_post.prf \
		../../../local/share/qt4/mkspecs/features/unix/thread.prf \
		../../../local/share/qt4/mkspecs/features/warn_on.prf \
		../../../local/share/qt4/mkspecs/features/qt.prf \
		../../../local/share/qt4/mkspecs/features/moc.prf \
		../../../local/share/qt4/mkspecs/features/resources.prf \
		../../../local/share/qt4/mkspecs/features/uic.prf \
		../../../local/share/qt4/mkspecs/features/yacc.prf \
		../../../local/share/qt4/mkspecs/features/lex.prf \
		../../../local/share/qt4/mkspecs/features/include_source_dir.prf \
		woWop.pro
QMAKE_TARGET  = woWop
DESTDIR       = 
TARGET        = woWop

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: woWop.pro  ../../../local/share/qt4/mkspecs/freebsd-g++/qmake.conf ../../../local/share/qt4/mkspecs/common/g++.conf \
		../../../local/share/qt4/mkspecs/common/unix.conf \
		../../../local/share/qt4/mkspecs/qconfig.pri \
		../../../local/share/qt4/mkspecs/modules/qt_phonon.pri \
		../../../local/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		../../../local/share/qt4/mkspecs/features/qt_functions.prf \
		../../../local/share/qt4/mkspecs/features/qt_config.prf \
		../../../local/share/qt4/mkspecs/features/exclusive_builds.prf \
		../../../local/share/qt4/mkspecs/features/default_pre.prf \
		../../../local/share/qt4/mkspecs/features/release.prf \
		../../../local/share/qt4/mkspecs/features/default_post.prf \
		../../../local/share/qt4/mkspecs/features/unix/thread.prf \
		../../../local/share/qt4/mkspecs/features/warn_on.prf \
		../../../local/share/qt4/mkspecs/features/qt.prf \
		../../../local/share/qt4/mkspecs/features/moc.prf \
		../../../local/share/qt4/mkspecs/features/resources.prf \
		../../../local/share/qt4/mkspecs/features/uic.prf \
		../../../local/share/qt4/mkspecs/features/yacc.prf \
		../../../local/share/qt4/mkspecs/features/lex.prf \
		../../../local/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/local/lib/qt4/libQtWebKit.prl \
		/usr/local/lib/qt4/libQtGui.prl \
		/usr/local/lib/qt4/libQtCore.prl
	$(QMAKE) -spec ../../../local/share/qt4/mkspecs/freebsd-g++ -o Makefile woWop.pro
../../../local/share/qt4/mkspecs/common/g++.conf:
../../../local/share/qt4/mkspecs/common/unix.conf:
../../../local/share/qt4/mkspecs/qconfig.pri:
../../../local/share/qt4/mkspecs/modules/qt_phonon.pri:
../../../local/share/qt4/mkspecs/modules/qt_webkit_version.pri:
../../../local/share/qt4/mkspecs/features/qt_functions.prf:
../../../local/share/qt4/mkspecs/features/qt_config.prf:
../../../local/share/qt4/mkspecs/features/exclusive_builds.prf:
../../../local/share/qt4/mkspecs/features/default_pre.prf:
../../../local/share/qt4/mkspecs/features/release.prf:
../../../local/share/qt4/mkspecs/features/default_post.prf:
../../../local/share/qt4/mkspecs/features/unix/thread.prf:
../../../local/share/qt4/mkspecs/features/warn_on.prf:
../../../local/share/qt4/mkspecs/features/qt.prf:
../../../local/share/qt4/mkspecs/features/moc.prf:
../../../local/share/qt4/mkspecs/features/resources.prf:
../../../local/share/qt4/mkspecs/features/uic.prf:
../../../local/share/qt4/mkspecs/features/yacc.prf:
../../../local/share/qt4/mkspecs/features/lex.prf:
../../../local/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/local/lib/qt4/libQtWebKit.prl:
/usr/local/lib/qt4/libQtGui.prl:
/usr/local/lib/qt4/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec ../../../local/share/qt4/mkspecs/freebsd-g++ -o Makefile woWop.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/woWop1.0.0 || $(MKDIR) .tmp/woWop1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/woWop1.0.0/ && $(COPY_FILE) --parents mainwindow.h treeitem.h treemodel.h .tmp/woWop1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp treeitem.cpp treemodel.cpp .tmp/woWop1.0.0/ && $(COPY_FILE) --parents mainwindow.ui .tmp/woWop1.0.0/ && (cd `dirname .tmp/woWop1.0.0` && $(TAR) woWop1.0.0.tar woWop1.0.0 && $(COMPRESS) woWop1.0.0.tar) && $(MOVE) `dirname .tmp/woWop1.0.0`/woWop1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/woWop1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_treemodel.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_treemodel.cpp
moc_mainwindow.cpp: mainwindow.h
	/usr/local/bin/moc-qt4 $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_treemodel.cpp: treemodel.h
	/usr/local/bin/moc-qt4 $(DEFINES) $(INCPATH) treemodel.h -o moc_treemodel.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui
	/usr/local/bin/uic-qt4 mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		ui_mainwindow.h \
		treemodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

treeitem.o: treeitem.cpp treeitem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o treeitem.o treeitem.cpp

treemodel.o: treemodel.cpp treeitem.h \
		treemodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o treemodel.o treemodel.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_treemodel.o: moc_treemodel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_treemodel.o moc_treemodel.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

